default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tour_move_development
  username: postgres
  password: 

test:
  <<: *default
  database: tour_move_test
  username: postgres
  password: 

production:
  <<: *default
  database: tour_move
  username: tour_move
  password: <%= ENV['TOUR_MOVE_DATABASE_PASSWORD'] %>
