default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tour_move_development
  username: tour_move
  password: 1234

test:
  <<: *default
  database: tour_move_test
  username: tour_move
  password: 1234

production:
  <<: *default
  database: tour_move
  username: tour_move
  password: 1234 # <%= ENV['TOUR_MOVE_DATABASE_PASSWORD'] %>
